---
- name: Download setup shell for nodejs
  get_url: url="https://deb.nodesource.com/setup_5.x" dest="/usr/local/src/setup_node.sh" mode=0755
  register: downloaded_setup

- name: find out if build is necessary.
  set_fact:
    need_to_setup: "{{ downloaded_setup | changed }}"

- name: Setup nodejs
  shell: /usr/local/src/setup_node.sh
  when: need_to_setup

- name: Install nodejs
  apt: name=nodejs state=latest
