---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.slim"
  - "**.js"
  - "**.jsx"
exclude_paths:
- config/
- db/
- log/
- node_modules/
- bower_components/
- spec/
- vendor/
- public/
- webpack/js/vendor/
- .idea
