---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scsslint:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.slim"
  - "**.js"
  - "**.jsx"
exclude_paths:
- .idea
- app/assets/javascripts/ckeditor
- app/assets/javascripts/webpack
- bower_components/
- config/
- db/
- frontend/css/vendor/
- frontend/js/vendor/
- frontend/js/vuejs/summary-editor.js
- log/
- node_modules/
- public/
- spec/
- vendor/
- webpack.config.babel.js
