AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'app/models/ckeditor/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/*'
    - 'spec/**/*'
    - 'Guardfile'
    - 'vagrant/**/*'
    - 'node_modules/**/*'
    - 'config.ru'

Rails:
  Enabled: true

# ファイル冒頭にコメント不要
Style/Documentation:
  Enabled: false

# 1行を120文字まで許可
LineLength:
  Max: 120

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# Perlスタイルの部分文字列の取得を許可
Style/PerlBackrefs:
    Enabled: false

# 複数行のラムダ式にアロー演算子を許可
Style/Lambda:
  Enabled: false

# 複数行のメソッド呼び出しのインデントをチェックしない
Style/MultilineMethodCallIndentation:
  Enabled: false

# 後置if/unlessに変換できるのをチェックしない
Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

