version: '2'
services:
  web: &app_base
    build:
      context: .
      dockerfile: ./Dockerfile.rails.development
    ports:
      - 3000:3000
    command: rails s -b 0.0.0.0
    depends_on:
      - db
    volumes:
      - .:/usr/local/app
      - /usr/local/app/tmp/pids
    environment:
      DATABASE_URL: mysql2://root:pw@db:3306

  node:
    build:
      context: .
      dockerfile: ./Dockerfile.node.development
    ports:
      - 3500:3500
    command: npm run build:dev
    volumes:
      - .:/usr/local/app

  db:
    image: tigberd/mysql-locale-jp
    ports:
      - 3306:3306
    volumes:
      - ./docker_mount/db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pw

  spring:
    <<: *app_base
    ports: []
    command: spring server
    stdin_open: true
    tty: true
    pid: host
    environment:
      DATABASE_URL: mysql2://root:pw@db:3306
      SPRING_SOCKET: /tmp/spring/spring.sock
    volumes:
      - .:/usr/local/app
      - spring:/tmp/spring

volumes:
  spring:
