version: '2'
services:
  db:
    image: tigberd/mysql-locale-jp
    ports:
      - "3306:3306"
    volumes:
      - ./docker_mount/db/:/var/lib/mysql
      - ./db/docker_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=pw
