VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.network :private_network, ip: '192.168.33.10'
  config.vm.network 'forwarded_port', guest: 3000, host: 3000
  config.vm.network 'forwarded_port', guest: 3001, host: 3001
  config.vm.network 'forwarded_port', guest: 3306, host: 3306
  config.vm.network 'forwarded_port', guest: 6379, host: 6379

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
    vb.customize ['modifyvm', :id, '--memory', '2048']
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.limit = 'all'
    ansible.playbook = 'provision/development.yml'
    ansible.inventory_path = 'provision/hosts'
    ansible.install = true
  end

  config.vm.synced_folder '../', '/home/vagrant/rails'
end
