---
- name: Set the locate
  shell: locale-gen ja_JP.UTF-8 && update-locale LANG=ja_JP.UTF-8 LC_ALL=ja_JP.UTF-8

- name: Install NTP
  apt: name=ntp state=latest
- name: Configure NTP
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
- name: Be sure NTPd is running and enabled
  service: name=ntp state=started enabled=yes
