---
- name: Set the locate
  shell: locale-gen ja_JP.UTF-8 && update-locale LANG=ja_JP.UTF-8 LC_ALL=ja_JP.UTF-8

- name: Install NTP
  apt: name=ntp state=latest
- name: Configure NTP
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
- name: Be sure NTPd is running and enabled
  service: name=ntp state=started enabled=yes
- name: restart ntpd
  service: name=ntp state=restarted

- name: Install Vim
  apt: name={{ item }} state=latest
  with_items:
    - vim-gnome

- name: Install mysql
  apt: name={{ item }} state=latest
  with_items:
    - libmysqld-dev

- name: Install rails and bundler
  become_user: "{{ rbenv_user }}"
  gem: name={{ item }} executable=~/.rbenv/shims/gem user_install=False
  with_items:
    - bundler

- name: Install javascript tools
  npm: name={{ item }} state=latest global=yes
  with_items:
    - bower
    - gulp
