default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  host: 127.0.0.1
  database: reversal
  username: reversal
  password: pw

test:
  <<: *default
  host: 127.0.0.1
  database: test

production:
  <<: *default
  host:     <%= ENV['RAILS_DATABASE_HOST'] %>
  database: reversal
  username: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
