default: &default
  adapter: mysql2
  encoding: utf8
  username: reversal
  pool: 5

development:
  <<: *default
  host: reversal
  database: reversal
  password: pw

test:
  <<: *default
  host: reversal
  database: test
  password: pw

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
