Chara.create!([
  {name: "ソル", en_name: "Sol", abbrev: 'so'},
  {name: "カイ", en_name: "Ky", abbrev: 'ky'},
  {name: "メイ", en_name: "May", abbrev: 'ma'},
  {name: "ミリア", en_name: "Millia", abbrev: 'mi'},
  {name: "ザトー", en_name: "Zato", abbrev: 'za'},
  {name: "ポチョムキン", en_name: "Potemkin", abbrev: 'po'},
  {name: "チップ", en_name: "Chipp", abbrev: 'ch'},
  {name: "ファウスト", en_name: "Faust", abbrev: 'fa'},
  {name: "アクセル", en_name: "Axl", abbrev: 'ax'},
  {name: "スレイヤー", en_name: "Slayer", abbrev: 'sl'},
  {name: "ヴェノム", en_name: "Venom", abbrev: 've'},
  {name: "イノ", en_name: "Ino", abbrev: 'in'},
  {name: "ベッドマン", en_name: "Bedman", abbrev: 'be'},
  {name: "ラムレザル", en_name: "Ramlethal", abbrev: 'ra'},
  {name: "シン", en_name: "Sin", abbrev: 'si'},
  {name: "エルフェルト", en_name: "Elphelt", abbrev: 'el'},
  {name: "レオ", en_name: "Leo", abbrev: 'le'},
  {name: "ジョニー", en_name: "Johnny", abbrev: 'jo'},
  {name: "ジャックオー", en_name: "Jack-O", abbrev: 'jc'},
  {name: "ジャム", en_name: "Jam", abbrev: 'ja'},
  {name: "クム", en_name: "Kum", abbrev: 'ku'},
  {name: "レイヴン", en_name: "Raven", abbrev: 'rv'},
  {name: "ディズィー", en_name: "Dizzy", abbrev: 'di'}
])

Rank.create!([
  {rank: "初段未満"},
  {rank: "初段"},
  {rank: "2段"},
  {rank: "3段"},
  {rank: "4段"},
  {rank: "5段"},
  {rank: "6段"},
  {rank: "7段"},
  {rank: "8段"},
  {rank: "9段"},
  {rank: "10段"},
  {rank: "11段"},
  {rank: "12段"},
  {rank: "13段"},
  {rank: "14段"},
  {rank: "15段"},
  {rank: "16段"},
  {rank: "17段"},
  {rank: "18段"},
  {rank: "19段"},
  {rank: "20段"},
  {rank: "21段"},
  {rank: "22段"},
  {rank: "23段"},
  {rank: "24段"},
  {rank: "25段"},
  {rank: "賞金首"},
  {rank: "聖人"},
  {rank: "王者"},
  {rank: "暴君"},
  {rank: "闘神"}
])

SlackChannel.create!([
  {cid: "C136K4X5Y", name: "aaa"},
  {cid: "C135T8JT0", name: "axl"},
  {cid: "C135R2WMS", name: "bedman"},
  {cid: "C1361G745", name: "chipp"},
  {cid: "C136C6Y3C", name: "dizzy"},
  {cid: "C1360FFRV", name: "elphelt"},
  {cid: "C135T85U6", name: "faust"},
  {cid: "C048NEW63", name: "feedback"},
  {cid: "C135W9KRA", name: "hiro_test"},
  {cid: "C136C2JUS", name: "ino"},
  {cid: "C135Z4GN4", name: "jack-o"},
  {cid: "C135R4TKN", name: "jam"},
  {cid: "C1360FYMD", name: "johnny"},
  {cid: "C135Z55GQ", name: "kum"},
  {cid: "C135YUUF2", name: "ky"},
  {cid: "C135R47PW", name: "leo"},
  {cid: "C135QV5JQ", name: "may"},
  {cid: "C135YUZFA", name: "millia"},
  {cid: "C1364A5J4", name: "nagememo"},
  {cid: "C1368HMS9", name: "nakamuramemo"},
  {cid: "C047KK2JG", name: "notify"},
  {cid: "C134K6DMH", name: "potemkin"},
  {cid: "C134K8J83", name: "ramlethal"},
  {cid: "C047KK2JL", name: "random"},
  {cid: "C1366E6BB", name: "raven"},
  {cid: "C1360EYPR", name: "sin"},
  {cid: "C1361HDTP", name: "slayer"},
  {cid: "C1361E1QD", name: "sol"},
  {cid: "C1488DMDW", name: "takamemo"},
  {cid: "C134K7TCK", name: "venom"},
  {cid: "C047L3QFU", name: "videos"},
  {cid: "C1360BCNT", name: "zato"}
])

Twitter2slackCondition.create!([
  {text: "#ソル攻略", slack_channel: SlackChannel.find_by(name: "sol")},
  {text: "#カイ攻略", slack_channel: SlackChannel.find_by(name: "ky")},
  {text: "#メイ攻略", slack_channel: SlackChannel.find_by(name: "may")},
  {text: "#ミリア攻略", slack_channel: SlackChannel.find_by(name: "millia")},
  {text: "#ザトー攻略", slack_channel: SlackChannel.find_by(name: "zato")},
  {text: "#ポチョムキン攻略", slack_channel: SlackChannel.find_by(name: "potemkin")},
  {text: "#チップ攻略", slack_channel: SlackChannel.find_by(name: "chipp")},
  {text: "#ファウスト攻略", slack_channel: SlackChannel.find_by(name: "faust")},
  {text: "#アクセル攻略", slack_channel: SlackChannel.find_by(name: "axl")},
  {text: "#ヴェノム攻略", slack_channel: SlackChannel.find_by(name: "venom")},
  {text: "#スレイヤー攻略", slack_channel: SlackChannel.find_by(name: "slayer")},
  {text: "#イノ攻略", slack_channel: SlackChannel.find_by(name: "ino")},
  {text: "#ベッドマン攻略", slack_channel: SlackChannel.find_by(name: "bedman")},
  {text: "#ラムレザル攻略", slack_channel: SlackChannel.find_by(name: "ramlethal")},
  {text: "#シン攻略", slack_channel: SlackChannel.find_by(name: "sin")},
  {text: "#エルフェルト攻略", slack_channel: SlackChannel.find_by(name: "elphelt")},
  {text: "#レオ攻略", slack_channel: SlackChannel.find_by(name: "leo")},
  {text: "#ジョニー攻略", slack_channel: SlackChannel.find_by(name: "johnny")},
  {text: "#ジャックオー攻略", slack_channel: SlackChannel.find_by(name: "jack-o")},
  {text: "#ジャム攻略", slack_channel: SlackChannel.find_by(name: "jam")},
  {text: "#クム攻略", slack_channel: SlackChannel.find_by(name: "kum")},
  {text: "#レイヴン攻略", slack_channel: SlackChannel.find_by(name: "raven")},
  {text: "#ディズィー攻略", slack_channel: SlackChannel.find_by(name: "dizzy")},
  {text: "#GGXrd_SO", slack_channel: SlackChannel.find_by(name: "sol")},
  {text: "#GGXrd_KY", slack_channel: SlackChannel.find_by(name: "ky")},
  {text: "#GGXrd_MA", slack_channel: SlackChannel.find_by(name: "may")},
  {text: "#GGXrd_MI", slack_channel: SlackChannel.find_by(name: "millia")},
  {text: "#GGXrd_ZA", slack_channel: SlackChannel.find_by(name: "zato")},
  {text: "#GGXrd_PO", slack_channel: SlackChannel.find_by(name: "potemkin")},
  {text: "#GGXrd_CH", slack_channel: SlackChannel.find_by(name: "chipp")},
  {text: "#GGXrd_FA", slack_channel: SlackChannel.find_by(name: "faust")},
  {text: "#GGXrd_AX", slack_channel: SlackChannel.find_by(name: "axl")},
  {text: "#GGXrd_VE", slack_channel: SlackChannel.find_by(name: "venom")},
  {text: "#GGXrd_SL", slack_channel: SlackChannel.find_by(name: "slayer")},
  {text: "#GGXrd_IN", slack_channel: SlackChannel.find_by(name: "ino")},
  {text: "#GGXrd_BE", slack_channel: SlackChannel.find_by(name: "bedman")},
  {text: "#GGXrd_RA", slack_channel: SlackChannel.find_by(name: "ramlethal")},
  {text: "#GGXrd_SI", slack_channel: SlackChannel.find_by(name: "sin")},
  {text: "#GGXrd_EL", slack_channel: SlackChannel.find_by(name: "elphelt")},
  {text: "#GGXrd_LE", slack_channel: SlackChannel.find_by(name: "leo")},
  {text: "#GGXrd_JO", slack_channel: SlackChannel.find_by(name: "johnny")},
  {text: "#GGXrd_JC", slack_channel: SlackChannel.find_by(name: "jack-o")},
  {text: "#GGXrd_JA", slack_channel: SlackChannel.find_by(name: "jam")},
  {text: "#GGXrd_KU", slack_channel: SlackChannel.find_by(name: "kum")},
  {text: "#GGXrd_RV", slack_channel: SlackChannel.find_by(name: "raven")},
  {text: "#GGXrd_DI", slack_channel: SlackChannel.find_by(name: "dizzy")}
])

VideoSiteSearchCondition.create!([
  {word: "GGXrd", video_site: "nicovideo"},
  {word: "GGXrdR", video_site: "nicovideo"}
])

Room.create!([
  {name: "Sol", url: "sol"},
  {name: "Ky", url: "ky"},
  {name: "May", url: "may"},
  {name: "Millia", url: "millia"},
  {name: "Zato", url: "zato"},
  {name: "Potemkin", url: "potemkin"},
  {name: "Chipp", url: "chipp"},
  {name: "Faust", url: "faust"},
  {name: "Axl", url: "axl"},
  {name: "Slayer", url: "slayer"},
  {name: "Venom", url: "venom"},
  {name: "Ino", url: "ino"},
  {name: "Bedman", url: "bedman"},
  {name: "Ramlethal", url: "ramlethal"},
  {name: "Sin", url: "sin"},
  {name: "Elphelt", url: "elphelt"},
  {name: "Leo", url: "leo"},
  {name: "Johnny", url: "johnny"},
  {name: "Jack-O", url: "jack-o"},
  {name: "Jam", url: "jam"},
  {name: "Kum", url: "kum"},
  {name: "Raven", url: "raven"},
  {name: "Dizzy", url: "dizzy"}
])

Mikado23onEntry.create!([
  {area: 'east', chara: Chara.find_by(en_name: 'Sol'),       entry_num: 1, name: 'ロイ', twitter: '@Ume_MK2', rank: Rank.find_by(rank: '王者'), comment: '盛り上げに貢献したい！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Sol'),       entry_num: 2, name: 'NOB', twitter: '@nobsol_7', rank: Rank.find_by(rank: '25段'), comment: '東京シンガポール遠征で金切符取ってきます！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Ky'),        entry_num: 1, name: 'りおん', twitter: '@lionhiro', rank: Rank.find_by(rank: '王者'), comment: '楽しみです、よろしくお願いします！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Ky'),        entry_num: 2, name: 'あいん', twitter: '@ainman0107', rank: Rank.find_by(rank: '王者'), comment: '神奈川 とりあえずエントリーをば。'},
  {area: 'east', chara: Chara.find_by(en_name: 'May'),       entry_num: 1, name: 'SHO', twitter: '@0827Sho', rank: Rank.find_by(rank: '22段'), comment: '神奈川　xrdでのこういったイベントは出た事ないので参加してみたいです！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Millia'),    entry_num: 1, name: '中村', twitter: '@nakamura_mi', rank: Rank.find_by(rank: '王者'), comment: '全力で楽しみます！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Millia'),    entry_num: 2, name: 'JUN', twitter: '@hara_yu', rank: Rank.find_by(rank: '聖人'), comment: '東京、前作での23onはとても楽しめましたのて参加したいと思います！プレーヤー人口も増えましたし、皆さんで盛り上げていきましょう！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Millia'),    entry_num: 3, name: 'とるそ', twitter: '', rank: Rank.find_by(rank: '初段'), comment: ''},
  {area: 'east', chara: Chara.find_by(en_name: 'Zato'),      entry_num: 1, name: '小川', twitter: '@ogawazato', rank: Rank.find_by(rank: '闘神'), comment: ''},
  {area: 'east', chara: Chara.find_by(en_name: 'Potemkin'),  entry_num: 1, name: 'FAB', twitter: '@gou4th_fab', rank: Rank.find_by(rank: '暴君'), comment: '東京'},
  {area: 'east', chara: Chara.find_by(en_name: 'Potemkin'),  entry_num: 2, name: 'コンソメ', twitter: '@consomme0914', rank: Rank.find_by(rank: '王者'), comment: '神奈川　一応参加表明。参加できなくても当日は遊びに行きます'},
  {area: 'east', chara: Chara.find_by(en_name: 'Potemkin'),  entry_num: 3, name: 'こうたろうバスター', twitter: '@zexedaze', rank: Rank.find_by(rank: '22段'), comment: '群馬です出てみたいです'},
  {area: 'east', chara: Chara.find_by(en_name: 'Potemkin'),  entry_num: 4, name: '下の中', twitter: '@genotyu', rank: Rank.find_by(rank: '22段'), comment: '東京　当日の予定はわかりませんが　アレなポチョをお見せできるように頑張ります。'},
  {area: 'east', chara: Chara.find_by(en_name: 'Chipp'),     entry_num: 1, name: 'サミット', twitter: '@summit812', rank: Rank.find_by(rank: '闘神'), comment: '千葉 楽しみたいですー！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Chipp'),     entry_num: 2, name: '遠藤', twitter: '@hangeyou', rank: Rank.find_by(rank: '暴君'), comment: 'よろしくお願いします。'},
  {area: 'east', chara: Chara.find_by(en_name: 'Chipp'),     entry_num: 3, name: '苺丸', twitter: '@ichigo1502000', rank: Rank.find_by(rank: '22段'), comment: '神奈川 久々にイベント参加したいと思います'},
  {area: 'east', chara: Chara.find_by(en_name: 'Faust'),     entry_num: 1, name: 'ナゲ', twitter: '@nage_pink', rank: Rank.find_by(rank: '闘神'), comment: 'お祭りに参加したい！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Faust'),     entry_num: 2, name: 'がぞう', twitter: '@gazou012', rank: Rank.find_by(rank: '暴君'), comment: '神奈川　家庭用からの新キャラを潰すマン'},
  {area: 'east', chara: Chara.find_by(en_name: 'Faust'),     entry_num: 3, name: '大坂Ｂ', twitter: '@jiyouzi_souten', rank: Rank.find_by(rank: '聖人'), comment: '茨城 画面端のきたない撲滅バレーボール見たい？・・・見たくない？'},
  {area: 'east', chara: Chara.find_by(en_name: 'Axl'),       entry_num: 1, name: 'よーすけ', twitter: '@yousuke1455', rank: Rank.find_by(rank: '賞金首'), comment: '東京 枠があればぜひ参加したいです。'},
  {area: 'east', chara: Chara.find_by(en_name: 'Slayer'),    entry_num: 1, name: 'はせ', twitter: '@KamoneSoccer', rank: Rank.find_by(rank: '暴君'), comment: ''},
  {area: 'east', chara: Chara.find_by(en_name: 'Slayer'),    entry_num: 2, name: 'TAKA', twitter: '@mochida_tw', rank: Rank.find_by(rank: '25段'), comment: '盛り上げれるよう頑張りまっす！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Slayer'),    entry_num: 3, name: 'モガ', twitter: '@moga0425', rank: Rank.find_by(rank: '24段'), comment: 'うぃ'},
  {area: 'east', chara: Chara.find_by(en_name: 'Venom'),     entry_num: 1, name: '螢一', twitter: '@Kouji4', rank: Rank.find_by(rank: '聖人'), comment: 'すぐ下がるので聖人のうちに登録しておきます'},
  {area: 'east', chara: Chara.find_by(en_name: 'Venom'),     entry_num: 2, name: 'カメご', twitter: '@kamego_13', rank: Rank.find_by(rank: '21段'), comment: '東京･神奈川'},
  {area: 'east', chara: Chara.find_by(en_name: 'Ino'),       entry_num: 1, name: 'おとうと', twitter: '@moccosbr', rank: Rank.find_by(rank: '暴君'), comment: '静岡 休みが取れたので参加したい！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Ino'),       entry_num: 2, name: 'トゥーリオ', twitter: '@ino_tsukai', rank: Rank.find_by(rank: '王者'), comment: '久々の23on'},
  {area: 'east', chara: Chara.find_by(en_name: 'Ino'),       entry_num: 3, name: '町', twitter: '@machi_ino', rank: Rank.find_by(rank: '25段'), comment: '神奈川　俺も団体戦でワイワイやりたいんだYO！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Bedman'),    entry_num: 1, name: '中洲ベッドマン(日の出～ラスト)', twitter: '@lox_monooki', rank: Rank.find_by(rank: '王者'), comment: '東側で九州勢をお出迎えします'},
  {area: 'east', chara: Chara.find_by(en_name: 'Bedman'),    entry_num: 2, name: '阿紫花', twitter: '@ashihana_ju', rank: Rank.find_by(rank: '王者'), comment: '東京 よろしくお願いします'},
  {area: 'east', chara: Chara.find_by(en_name: 'Bedman'),    entry_num: 3, name: 'なおとベッドマン', twitter: '@naoto_slowlife', rank: Rank.find_by(rank: '賞金首'), comment: '東京。出てみたい気持ちは人一倍。'},
  {area: 'east', chara: Chara.find_by(en_name: 'Ramlethal'), entry_num: 1, name: 'かっこう', twitter: '@kakkou_K', rank: Rank.find_by(rank: '暴君'), comment: '東京　団体戦は初めてなので出れたらいいな！宜しくお願いします！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Ramlethal'), entry_num: 2, name: 'ほひこ', twitter: '@an_hohiko', rank: Rank.find_by(rank: '賞金首'), comment: ''},
  {area: 'east', chara: Chara.find_by(en_name: 'Elphelt'),   entry_num: 1, name: 'ハンバーグ', twitter: '@icarus_squad', rank: Rank.find_by(rank: '闘神'), comment: '楽しそうなイベント！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Elphelt'),   entry_num: 2, name: 'ふも', twitter: '@humo_ah', rank: Rank.find_by(rank: '暴君'), comment: '参加したいです！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Elphelt'),   entry_num: 3, name: 'ます', twitter: '@Kedolino', rank: Rank.find_by(rank: '王者'), comment: '東京・神奈川。参加出来たら、全力でぶつかって楽しみたいです！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Sin'),       entry_num: 1, name: 'ヒロキ', twitter: '@hiroki_yukari', rank: Rank.find_by(rank: '賞金首'), comment: '埼玉、東京 まだ参加できるかわかりませんが、興味ありますので表明させていただきます。'},
  {area: 'east', chara: Chara.find_by(en_name: 'Leo'),       entry_num: 1, name: 'ほっさ', twitter: '@hontosumanhossa', rank: Rank.find_by(rank: '聖人'), comment: '神奈川 団体戦すごく楽しみです。'},
  {area: 'east', chara: Chara.find_by(en_name: 'Leo'),       entry_num: 2, name: 'ゆうぞう', twitter: '@yuzoLEO', rank: Rank.find_by(rank: '賞金首'), comment: '東京 レオで荒らしたい'},
  {area: 'east', chara: Chara.find_by(en_name: 'Johnny'),    entry_num: 1, name: 'おぎちゃん', twitter: '@ogichanvv', rank: Rank.find_by(rank: '王者'), comment: ''},
  {area: 'east', chara: Chara.find_by(en_name: 'Johnny'),    entry_num: 2, name: 'じょにお', twitter: '@jonio_mikado', rank: Rank.find_by(rank: '賞金首'), comment: '東京　協力よろしくお願いします！！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Jam'),       entry_num: 1, name: 'てれさ', twitter: '@jamtsukaware', rank: Rank.find_by(rank: '闘神'), comment: '東京 嫌われ者でも大会出たい！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Jam'),       entry_num: 2, name: 'かるかる', twitter: '@chibita_chibit', rank: Rank.find_by(rank: '聖人'), comment: '★☆(*´з`*)☆★撲滅'},
  {area: 'east', chara: Chara.find_by(en_name: 'Kum'),       entry_num: 1, name: 'J.T', twitter: '@hauko_mmts', rank: Rank.find_by(rank: '25段'), comment: '家庭用勢'},
  {area: 'east', chara: Chara.find_by(en_name: 'Kum'),       entry_num: 2, name: 'まろし', twitter: '@maroshijapa', rank: Rank.find_by(rank: '25段'), comment: ''},
  {area: 'east', chara: Chara.find_by(en_name: 'Raven'),     entry_num: 1, name: 'ザディ', twitter: '@SOorXTC', rank: Rank.find_by(rank: '王者'), comment: '大型の団体戦があれば、ぜひ参加したいと思っていました。宜しくお願いします！'},
  {area: 'east', chara: Chara.find_by(en_name: 'Dizzy'),     entry_num: 1, name: '押田撲滅委員会会長カズキ', twitter: '@cucumbergod', rank: Rank.find_by(rank: '23段'), comment: '東京 23on23on1(FAB)と聞いてきました'},
  {area: 'east', chara: Chara.find_by(en_name: 'Dizzy'),     entry_num: 2, name: 'きっしー', twitter: '@kisshi_di', rank: Rank.find_by(rank: '20段'), comment: '東京 あんまりやってないけど'},
  {area: 'west', chara: Chara.find_by(en_name: 'May'),       entry_num: 1, name: 'けだこ', twitter: '@kedako_faital', rank: Rank.find_by(rank: '賞金首'), comment: '大阪　23onとか懐かしい！'},
  {area: 'west', chara: Chara.find_by(en_name: 'Millia'),    entry_num: 1, name: 'いな', twitter: '@prin721_5', rank: Rank.find_by(rank: '王者'), comment: '秋田　23onとか絶対面白い'},
  {area: 'west', chara: Chara.find_by(en_name: 'Zato'),      entry_num: 1, name: 'タイツ', twitter: '@tights1', rank: Rank.find_by(rank: '25段'), comment: '愛知　皆様のお力になれれば幸いです。'},
  {area: 'west', chara: Chara.find_by(en_name: 'Potemkin'),  entry_num: 1, name: '夏蜜柑', twitter: '@NATSU_ORANGE', rank: Rank.find_by(rank: '20段'), comment: '九州のポチョ使いです。'},
  {area: 'west', chara: Chara.find_by(en_name: 'Chipp'),     entry_num: 1, name: 'E.T', twitter: '', rank: Rank.find_by(rank: '賞金首'), comment: '福岡 全員ぶったおす！！'},
  {area: 'west', chara: Chara.find_by(en_name: 'Axl'),       entry_num: 1, name: 'イデさん（ネコミミ）', twitter: '@idemimi', rank: Rank.find_by(rank: '25段'), comment: '長崎　他にアクセルいなければ…'},
  {area: 'west', chara: Chara.find_by(en_name: 'Slayer'),    entry_num: 1, name: '手品師', twitter: '@neet1523', rank: Rank.find_by(rank: '聖人'), comment: '富山'},
  {area: 'west', chara: Chara.find_by(en_name: 'Venom'),     entry_num: 1, name: '勇', twitter: '@ISM_STRIKE', rank: Rank.find_by(rank: '闘神'), comment: '出れたら頑張ります！'},
  {area: 'west', chara: Chara.find_by(en_name: 'Ino'),       entry_num: 1, name: 'ウーゼン', twitter: '@uuzen', rank: Rank.find_by(rank: '聖人'), comment: '出れたら頑張ります！'},
  {area: 'west', chara: Chara.find_by(en_name: 'Bedman'),    entry_num: 1, name: 'さばみそ', twitter: '@abas_6101', rank: Rank.find_by(rank: '暴君'), comment: 'アーチスト代表として参加表明します( ・∇・)'},
  {area: 'west', chara: Chara.find_by(en_name: 'Bedman'),    entry_num: 2, name: 'みつる', twitter: '@P_mitsuru', rank: Rank.find_by(rank: '25段'), comment: '相談寝室実践編、見せてやらあ！！　　愛知'},
  {area: 'west', chara: Chara.find_by(en_name: 'Ramlethal'), entry_num: 1, name: 'saryu', twitter: '@saryu22492477', rank: Rank.find_by(rank: '賞金首'), comment: '山形 このようなイベントは中々ないので機会があれば参加したいと思います！'},
  {area: 'west', chara: Chara.find_by(en_name: 'Elphelt'),   entry_num: 1, name: 'きくた', twitter: '@lyrical_aba', rank: Rank.find_by(rank: '賞金首'), comment: '新潟'},
  {area: 'west', chara: Chara.find_by(en_name: 'Sin'),       entry_num: 1, name: 'DC', twitter: '@zikund_DC', rank: Rank.find_by(rank: '聖人'), comment: '宜しくお願いします。'},
  {area: 'west', chara: Chara.find_by(en_name: 'Sin'),       entry_num: 2, name: 'さだきよ', twitter: '@sadakiyo11kuina', rank: Rank.find_by(rank: '賞金首'), comment: '広島 嫁予選は笑顔で通過しました！よろしくお願いします！'},
  {area: 'west', chara: Chara.find_by(en_name: 'Leo'),       entry_num: 1, name: 'T5M7', twitter: '@7ghoti', rank: Rank.find_by(rank: '王者'), comment: '落ちた'},
  {area: 'west', chara: Chara.find_by(en_name: 'Jack-O'),    entry_num: 1, name: 'ぷれぷれ', twitter: '@77_pretzel', rank: Rank.find_by(rank: '聖人'), comment: '出来らぁ！'},
  {area: 'west', chara: Chara.find_by(en_name: 'Jam'),       entry_num: 1, name: 'じゃじゃ丸', twitter: '@jajamarujam', rank: Rank.find_by(rank: '暴君'), comment: '福岡'},
  {area: 'west', chara: Chara.find_by(en_name: 'Dizzy'),     entry_num: 1, name: 'まっきぃ', twitter: '@makkimen', rank: Rank.find_by(rank: '賞金首'), comment: '徳島　23on楽しみです！'}
])
