Chara.create!([
  {name: "ソル", en_name: "Sol"},
  {name: "カイ", en_name: "Ky"},
  {name: "メイ", en_name: "May"},
  {name: "ミリア", en_name: "Millia"},
  {name: "ザトー", en_name: "Zato"},
  {name: "ポチョムキン", en_name: "Potemkin"},
  {name: "チップ", en_name: "Chipp"},
  {name: "ファウスト", en_name: "Faust"},
  {name: "アクセル", en_name: "Axl"},
  {name: "スレイヤー", en_name: "Slayer"},
  {name: "ヴェノム", en_name: "Venom"},
  {name: "イノ", en_name: "Ino"},
  {name: "ベッドマン", en_name: "Bedman"},
  {name: "ラムレザル", en_name: "Ramlethal"},
  {name: "シン", en_name: "Sin"},
  {name: "エルフェルト", en_name: "Elphelt"},
  {name: "レオ", en_name: "Leo"},
  {name: "ジョニー", en_name: "Johnny"},
  {name: "ジャックオー", en_name: "Jack-O"},
  {name: "ジャム", en_name: "Jam"},
  {name: "クム", en_name: "Kum"},
  {name: "レイヴン", en_name: "Raven"},
  {name: "ディズィー", en_name: "Dizzy"}
])
Rank.create!([
  {rank: "初段未満"},
  {rank: "初段"},
  {rank: "2段"},
  {rank: "3段"},
  {rank: "4段"},
  {rank: "5段"},
  {rank: "6段"},
  {rank: "7段"},
  {rank: "8段"},
  {rank: "9段"},
  {rank: "10段"},
  {rank: "11段"},
  {rank: "12段"},
  {rank: "13段"},
  {rank: "14段"},
  {rank: "15段"},
  {rank: "16段"},
  {rank: "17段"},
  {rank: "18段"},
  {rank: "19段"},
  {rank: "20段"},
  {rank: "21段"},
  {rank: "22段"},
  {rank: "23段"},
  {rank: "24段"},
  {rank: "25段"},
  {rank: "賞金首"},
  {rank: "聖人"},
  {rank: "王者"},
  {rank: "暴君"},
  {rank: "闘神"}
])

SlackChannel.create!([
  {cid: "C136K4X5Y", name: "aaa", topic: "", is_archived: false},
  {cid: "C135T8JT0", name: "axl", topic: "", is_archived: false},
  {cid: "C135R2WMS", name: "bedman", topic: "", is_archived: false},
  {cid: "C1361G745", name: "chipp", topic: "", is_archived: false},
  {cid: "C136C6Y3C", name: "dizzy", topic: "", is_archived: false},
  {cid: "C1360FFRV", name: "elphelt", topic: "", is_archived: false},
  {cid: "C135T85U6", name: "faust", topic: "", is_archived: false},
  {cid: "C048NEW63", name: "feedback", topic: "サービス全体を通したフィードバックをください", is_archived: false},
  {cid: "C135W9KRA", name: "hiro_test", topic: "", is_archived: false},
  {cid: "C136C2JUS", name: "ino", topic: "", is_archived: false},
  {cid: "C135Z4GN4", name: "jack-o", topic: "", is_archived: false},
  {cid: "C135R4TKN", name: "jam", topic: "", is_archived: false},
  {cid: "C1360FYMD", name: "johnny", topic: "", is_archived: false},
  {cid: "C135Z55GQ", name: "kum", topic: "", is_archived: false},
  {cid: "C135YUUF2", name: "ky", topic: "", is_archived: false},
  {cid: "C135R47PW", name: "leo", topic: "", is_archived: false},
  {cid: "C135QV5JQ", name: "may", topic: "", is_archived: false},
  {cid: "C135YUZFA", name: "millia", topic: "", is_archived: false},
  {cid: "C1364A5J4", name: "nagememo", topic: "", is_archived: false},
  {cid: "C1368HMS9", name: "nakamuramemo", topic: "", is_archived: false},
  {cid: "C047KK2JG", name: "notify", topic: "全体通知用", is_archived: false},
  {cid: "C134K6DMH", name: "potemkin", topic: "", is_archived: false},
  {cid: "C134K8J83", name: "ramlethal", topic: "", is_archived: false},
  {cid: "C047KK2JL", name: "random", topic: "雑談など", is_archived: false},
  {cid: "C1366E6BB", name: "raven", topic: "", is_archived: false},
  {cid: "C1360EYPR", name: "sin", topic: "", is_archived: false},
  {cid: "C1361HDTP", name: "slayer", topic: "", is_archived: false},
  {cid: "C1361E1QD", name: "sol", topic: "", is_archived: false},
  {cid: "C1488DMDW", name: "takamemo", topic: "", is_archived: false},
  {cid: "C134K7TCK", name: "venom", topic: "", is_archived: false},
  {cid: "C047L3QFU", name: "videos", topic: "動画のアップロード通知", is_archived: false},
  {cid: "C1360BCNT", name: "zato", topic: "", is_archived: false}
])

Twitter2slackCondition.create!([
  {text: "#ソル攻略", slack_channel: SlackChannel.find_by(name: "sol")},
  {text: "#カイ攻略", slack_channel: SlackChannel.find_by(name: "ky")},
  {text: "#メイ攻略", slack_channel: SlackChannel.find_by(name: "may")},
  {text: "#ミリア攻略", slack_channel: SlackChannel.find_by(name: "millia")},
  {text: "#ザトー攻略", slack_channel: SlackChannel.find_by(name: "zato")},
  {text: "#ポチョムキン攻略", slack_channel: SlackChannel.find_by(name: "potemkin")},
  {text: "#チップ攻略", slack_channel: SlackChannel.find_by(name: "chipp")},
  {text: "#ファウスト攻略", slack_channel: SlackChannel.find_by(name: "faust")},
  {text: "#アクセル攻略", slack_channel: SlackChannel.find_by(name: "axl")},
  {text: "#ヴェノム攻略", slack_channel: SlackChannel.find_by(name: "venom")},
  {text: "#スレイヤー攻略", slack_channel: SlackChannel.find_by(name: "slayer")},
  {text: "#イノ攻略", slack_channel: SlackChannel.find_by(name: "ino")},
  {text: "#ベッドマン攻略", slack_channel: SlackChannel.find_by(name: "bedman")},
  {text: "#ラムレザル攻略", slack_channel: SlackChannel.find_by(name: "ramlethal")},
  {text: "#シン攻略", slack_channel: SlackChannel.find_by(name: "sin")},
  {text: "#エルフェルト攻略", slack_channel: SlackChannel.find_by(name: "elphelt")},
  {text: "#レオ攻略", slack_channel: SlackChannel.find_by(name: "leo")},
  {text: "#ジョニー攻略", slack_channel: SlackChannel.find_by(name: "johnny")},
  {text: "#ジャックオー攻略", slack_channel: SlackChannel.find_by(name: "jack-o")},
  {text: "#ジャム攻略", slack_channel: SlackChannel.find_by(name: "jam")},
  {text: "#クム攻略", slack_channel: SlackChannel.find_by(name: "kum")},
  {text: "#レイヴン攻略", slack_channel: SlackChannel.find_by(name: "raven")},
  {text: "#ディズィー攻略", slack_channel: SlackChannel.find_by(name: "dizzy")}
])

VideoSiteSearchCondition.create!([
  {word: "GGXrd", video_site: "nicovideo"}
])
