Chara.create!([
  {name: "ソル", en_name: "Sol"},
  {name: "カイ", en_name: "Ky"},
  {name: "メイ", en_name: "May"},
  {name: "ミリア", en_name: "Millia"},
  {name: "ザトー", en_name: "Zato"},
  {name: "ポチョムキン", en_name: "Potemkin"},
  {name: "チップ", en_name: "Chipp"},
  {name: "ファウスト", en_name: "Faust"},
  {name: "アクセル", en_name: "Axl"},
  {name: "スレイヤー", en_name: "Slayer"},
  {name: "ヴェノム", en_name: "Venom"},
  {name: "イノ", en_name: "Ino"},
  {name: "ベッドマン", en_name: "Bedman"},
  {name: "ラムレザル", en_name: "Ramlethal"},
  {name: "シン", en_name: "Sin"},
  {name: "エルフェルト", en_name: "Elphelt"},
  {name: "レオ", en_name: "Leo"},
  {name: "ジョニー", en_name: "Johnny"},
  {name: "ジャックオー", en_name: "Jack-O"},
  {name: "ジャム", en_name: "Jam"},
  {name: "クム", en_name: "Kum"},
  {name: "レイヴン", en_name: "Raven"},
  {name: "ディズィー", en_name: "Dizzy"}
])

Rank.create!([
  {rank: "初段未満"},
  {rank: "初段"},
  {rank: "2段"},
  {rank: "3段"},
  {rank: "4段"},
  {rank: "5段"},
  {rank: "6段"},
  {rank: "7段"},
  {rank: "8段"},
  {rank: "9段"},
  {rank: "10段"},
  {rank: "11段"},
  {rank: "12段"},
  {rank: "13段"},
  {rank: "14段"},
  {rank: "15段"},
  {rank: "16段"},
  {rank: "17段"},
  {rank: "18段"},
  {rank: "19段"},
  {rank: "20段"},
  {rank: "21段"},
  {rank: "22段"},
  {rank: "23段"},
  {rank: "24段"},
  {rank: "25段"},
  {rank: "賞金首"},
  {rank: "聖人"},
  {rank: "王者"},
  {rank: "暴君"},
  {rank: "闘神"}
])

SlackChannel.create!([
  {cid: "C136K4X5Y", name: "aaa"},
  {cid: "C135T8JT0", name: "axl"},
  {cid: "C135R2WMS", name: "bedman"},
  {cid: "C1361G745", name: "chipp"},
  {cid: "C136C6Y3C", name: "dizzy"},
  {cid: "C1360FFRV", name: "elphelt"},
  {cid: "C135T85U6", name: "faust"},
  {cid: "C048NEW63", name: "feedback"},
  {cid: "C135W9KRA", name: "hiro_test"},
  {cid: "C136C2JUS", name: "ino"},
  {cid: "C135Z4GN4", name: "jack-o"},
  {cid: "C135R4TKN", name: "jam"},
  {cid: "C1360FYMD", name: "johnny"},
  {cid: "C135Z55GQ", name: "kum"},
  {cid: "C135YUUF2", name: "ky"},
  {cid: "C135R47PW", name: "leo"},
  {cid: "C135QV5JQ", name: "may"},
  {cid: "C135YUZFA", name: "millia"},
  {cid: "C1364A5J4", name: "nagememo"},
  {cid: "C1368HMS9", name: "nakamuramemo"},
  {cid: "C047KK2JG", name: "notify"},
  {cid: "C134K6DMH", name: "potemkin"},
  {cid: "C134K8J83", name: "ramlethal"},
  {cid: "C047KK2JL", name: "random"},
  {cid: "C1366E6BB", name: "raven"},
  {cid: "C1360EYPR", name: "sin"},
  {cid: "C1361HDTP", name: "slayer"},
  {cid: "C1361E1QD", name: "sol"},
  {cid: "C1488DMDW", name: "takamemo"},
  {cid: "C134K7TCK", name: "venom"},
  {cid: "C047L3QFU", name: "videos"},
  {cid: "C1360BCNT", name: "zato"}
])

Twitter2slackCondition.create!([
  {text: "#ソル攻略", slack_channel: SlackChannel.find_by(name: "sol")},
  {text: "#カイ攻略", slack_channel: SlackChannel.find_by(name: "ky")},
  {text: "#メイ攻略", slack_channel: SlackChannel.find_by(name: "may")},
  {text: "#ミリア攻略", slack_channel: SlackChannel.find_by(name: "millia")},
  {text: "#ザトー攻略", slack_channel: SlackChannel.find_by(name: "zato")},
  {text: "#ポチョムキン攻略", slack_channel: SlackChannel.find_by(name: "potemkin")},
  {text: "#チップ攻略", slack_channel: SlackChannel.find_by(name: "chipp")},
  {text: "#ファウスト攻略", slack_channel: SlackChannel.find_by(name: "faust")},
  {text: "#アクセル攻略", slack_channel: SlackChannel.find_by(name: "axl")},
  {text: "#ヴェノム攻略", slack_channel: SlackChannel.find_by(name: "venom")},
  {text: "#スレイヤー攻略", slack_channel: SlackChannel.find_by(name: "slayer")},
  {text: "#イノ攻略", slack_channel: SlackChannel.find_by(name: "ino")},
  {text: "#ベッドマン攻略", slack_channel: SlackChannel.find_by(name: "bedman")},
  {text: "#ラムレザル攻略", slack_channel: SlackChannel.find_by(name: "ramlethal")},
  {text: "#シン攻略", slack_channel: SlackChannel.find_by(name: "sin")},
  {text: "#エルフェルト攻略", slack_channel: SlackChannel.find_by(name: "elphelt")},
  {text: "#レオ攻略", slack_channel: SlackChannel.find_by(name: "leo")},
  {text: "#ジョニー攻略", slack_channel: SlackChannel.find_by(name: "johnny")},
  {text: "#ジャックオー攻略", slack_channel: SlackChannel.find_by(name: "jack-o")},
  {text: "#ジャム攻略", slack_channel: SlackChannel.find_by(name: "jam")},
  {text: "#クム攻略", slack_channel: SlackChannel.find_by(name: "kum")},
  {text: "#レイヴン攻略", slack_channel: SlackChannel.find_by(name: "raven")},
  {text: "#ディズィー攻略", slack_channel: SlackChannel.find_by(name: "dizzy")}
])

VideoSiteSearchCondition.create!([
  {word: "GGXrd", video_site: "nicovideo"},
  {word: "GGXrdR", video_site: "nicovideo"}
])

Room.create!([
  {name: "Sol", url: "sol"},
  {name: "Ky", url: "ky"},
  {name: "May", url: "may"},
  {name: "Millia", url: "millia"},
  {name: "Zato", url: "zato"},
  {name: "Potemkin", url: "potemkin"},
  {name: "Chipp", url: "chipp"},
  {name: "Faust", url: "faust"},
  {name: "Axl", url: "axl"},
  {name: "Slayer", url: "slayer"},
  {name: "Venom", url: "venom"},
  {name: "Ino", url: "ino"},
  {name: "Bedman", url: "bedman"},
  {name: "Ramlethal", url: "ramlethal"},
  {name: "Sin", url: "sin"},
  {name: "Elphelt", url: "elphelt"},
  {name: "Leo", url: "leo"},
  {name: "Johnny", url: "johnny"},
  {name: "Jack-O", url: "jack-o"},
  {name: "Jam", url: "jam"},
  {name: "Kum", url: "kum"},
  {name: "Raven", url: "raven"},
  {name: "Dizzy", url: "dizzy"}
])
